defaults:
  - exp: setup1
  - _self_

# Active Learning
budget: 800
initial_budget: 100
n_avg: [1,2,3,4]
n_samples: 100
sample_first: False

# Example use: VAAL where it is model agnostic
load_queries: False
save_queries: False

# General setup
batch_size: 32
seed: 41
AL_methods: ["Uncertainty"]
TaskLearners: ["Simple"]
early_stop: 50
use_navg_as_DR: False
use_plots: False

# Tasklearner
n_class: 50
num_epochs: 300

# Paths
paths:
  train: data/processed/ESC50/train.csv
  test: data/processed/ESC50/test.csv


# Hyperparameter optimization
n_folds: 5

Simple:
  train: data/processed/ESC50/train_pca.pt
  test: data/processed/ESC50/test_pca.pt
  train_vaal: data/processed/ESC50/test_32x32
  test_vaal: data/processed/ESC50/test_32x32
  DR: 700
  learning_rates: [0.001, 0.0005, 0.0002, 0.0001]
  weight_decays: [0.01, 0.001, 0.0001, 0.00005]
  Optimizer: 'Adam'
  aud_conf: {}

CNN:
  train: data/processed/ESC50/train_128
  test: data/processed/ESC50/test_498
  train_vaal: data/processed/ESC50/train_128
  test_vaal: data/processed/ESC50/train_128
  DR: False
  learning_rates: [0.001, 0.0005, 0.0002, 0.0001]
  weight_decays: [0.01, 0.001, 0.0001, 0.00005]
  Optimizer: 'Adam'


vaal:
  dataset_size: 1600
