defaults:
  - exp: setup1
  - _self_

# Active Learning
budget: 30
initial_budget: 10
n_avg: 3
n_samples: 4


# General setup
batch_size: 5
seed: 41
AL_methods: ["VAAL"]
TaskLearners: ["Simple"]
early_stop: 40
use_navg_as_DR: False

# Tasklearner
n_class: 3
num_epochs: 2

# Paths
paths:
  train: data/processed/ESC50_3Class/train.csv
  test: data/processed/ESC50_3Class/test.csv


# Hyperparameter optimization
n_folds: 2

Simple:
  train: data/processed/ESC50_3Class/train_pca.pt
  test: data/processed/ESC50_3Class/test_pca.pt
  train_vaal: data/processed/ESC50_3Class/train_128
  test_vaal: data/processed/ESC50_3Class/test_128
  DR: 20
  learning_rates: [0.01,0.001,0.0002,0.0001]
  weight_decays: [0.001,0.0005,0.0001,0.00005]
  Optimizer: 'Adam'
  aud_conf: {}

CNN:
  train: data/processed/ESC50/train
  test: data/processed/ESC50/test
  train_vaal: data/processed/ESC50/train_resized
  test_vaal: data/processed/ESC50/test_resized
  DR: False
  learning_rates: [0.001, 0.0005, 0.0002, 0.0001]
  #learning_rates: [0.05]
  weight_decays: [0.01, 0.001, 0.0005, 0.0001, 0.00005]
  #weight_decays: [0.00005]
  Optimizer: 'Adam'
  aud_conf: {'n_mels': 128, 'target_length': 1100, 'dataset_mean': -6.019767, 'dataset_std': 5.5729656}


vaal:
  dataset_size: 96
  spectrogram_length: 128