defaults:
  - exp: setup1
  - _self_

# Active Learning
budget: 1000
initial_budget: 200
n_avg: 5
n_samples: 100
sample_first: "Random/Simple" # 'AL_method/TaskLearner' for the folder you want to sample from

# Example use: VAAL where it is model agnostic
load_queries: False # Path or False
save_queries: False # True or False

# General setup
dataset_folder: data/processed/WSA1K
batch_size: 32
seed: 41
AL_methods: ["Random","Uncertainty", "Uncertain+Random", "VAAL"] # 
TaskLearners: ["Simple"] # ,"MobileNet"
early_stop: 50

# Extra genaeral options
use_navg_as_DR: False
use_plots: False

# Tasklearner
n_class: 7
num_epochs: 300

# Paths
paths:
  train: ${dataset_folder}/train.csv
  test: ${dataset_folder}/test.csv

# Hyperparameter optimization
n_folds: 5

VAAL:
  dataset_size: 1600
  train: ${dataset_folder}/train_64x64
  test: ${dataset_folder}/test_64x64
  epochs: 150

Simple:
  train: ${dataset_folder}/PCA_498x128/train.pt
  test: ${dataset_folder}/PCA_498x128/test.pt
  DR: 700
  learning_rates: [0.01, 0.001, 0.0005]
  weight_decays: [0.01, 0.005, 0.001]
  Optimizer: 'Adam'
  aud_conf: {}

MobileNet:
  train: ${dataset_folder}/train_498x128
  test: ${dataset_folder}/test_498x128
  DR: False
  learning_rates: [0.0002, 0.0001, 0,00005]
  weight_decays:  [0.0001, 0.00005, 0.00001]
  Optimizer: 'Adam'


